Lets goooo

In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,f1_score,recall_score
from sklearn.model_selection import train_test_split as tt

In [55]:
class Logistic_Regression:
    def __init__(self,LearningRate=0.1,epochs=3000):
        self.lr=LearningRate
        self.w=None
        self.intercept=None
        self.coef=None
        self.epochs=epochs

    def sigmoid(self,z):
        z=np.clip(z,-500,500)
        return 1/(1+np.exp(-z))

    def fit(self,X,Y):
        X=np.insert(X,0,1,axis=1)
        self.w=np.ones(X.shape[1])
        m=X.shape[0]

        for i in range(self.epochs):
            y_pred=self.sigmoid(np.dot(X,self.w.T))
            self.w=self.w-(self.lr*np.dot(X.T,(y_pred-Y)))/m
            self.intercept=self.w[0]
            self.coef=self.w[1:]


    def predict(self,x):
        x=np.insert(x,0,1,axis=1)
        ans=self.sigmoid(np.dot(x,self.w.T))
        return (ans>0.5).astype(int)

In [ ]:
df=pd.read_csv('Social_Network_Ads.csv')
df['Gender']=df['Gender'].replace({'Male':1,'Female':0})
X=df[['Gender','Age','EstimatedSalary']].values
Y=df['Purchased']
x_train,x_test,y_train,y_test=tt(X,Y,test_size=0.2,random_state=2)
x_train=(x_train-np.mean(x_train))/np.std(x_train)
x_test=(x_test-np.mean(x_test))/np.std(x_test)

In [ ]:
lr=Logistic_Regression()
lr.fit(x_train,y_train)
lr.predict(x_test)

In [ ]:
model=LogisticRegression()
model.fit(x_train,y_train)
model.predict(x_test)

calculating accuracy

In [52]:
print(accuracy_score(model.predict(x_test),y_test))
print(accuracy_score(lr.predict(x_test),y_test))

0.7625
0.7625


In [57]:
print(lr.coef,lr.intercept)
print(model.coef_,model.intercept_)

[1.56221375 1.58284422 0.93166862] 0.07411770261220761
[[-0.00230559  0.02316827  0.91057384]] [-1.79320818]


observing confusion matrix

In [60]:
print(confusion_matrix(lr.predict(x_test),y_test))
print(confusion_matrix(model.predict(x_test),y_test))

[[46 17]
 [ 2 15]]
[[46 17]
 [ 2 15]]
